name: Deploy IAM Application

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      # Backend Spring Boot
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Spring Boot
        working-directory: iam-api
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests


      # Frontend React
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: iam-web/package-lock.json

      - name: Install React dependencies
        working-directory: iam-web
        run: |
          npm ci

      - name: Build React Application
        working-directory: iam-web
        run: |
          npm run build


      # Login GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}


      # Docker images
      - name: Build Backend Image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/iam-api:latest \
          ./iam-api


      - name: Build Frontend Image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/iam-web:latest \
          ./iam-web


      # Push images
      - name: Push Backend Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/iam-api:latest


      - name: Push Frontend Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/iam-web:latest