name: Deploy IAM Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Backend Spring Boot
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Spring Boot
        working-directory: iam-api
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Build Backend Docker Image
        run: |
          docker build -t iam-api ./iam-api


      # Frontend React
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: iam-web/package-lock.json

      - name: Install React dependencies
        working-directory: iam-web
        run: |
          npm ci

      - name: Build React Application
        working-directory: iam-web
        run: |
          npm run build

      - name: Build Frontend Docker Image
        run: |
          docker build -t iam-web ./iam-web